name: FirstLight
main: com.natoboram.spigot.firstlight.FirstLight
version: 1.1.0
author: NatoBoram
description: Stops the server when the last man standing quits.
api:
    - "1.7"
    - "1.8"
    - "1.9"
    - "1.10"
    - "1.11"
    - "1.12"
    - "1.13"
    - "1.14"
    - "1.15"
api-version: "1.15"
